# Generated by Django 4.2 on 2024-02-02 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_incolucradas', models.CharField(max_length=100)),
                ('tipo_de_servicio', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('duracion_de_tramite', models.IntegerField()),
                ('procedimiento', models.CharField(max_length=200)),
                ('require_attach', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='fut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('program', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
                ('cycle', models.CharField(max_length=2)),
                ('email', models.TextField(default='')),
                ('myrequest', models.TextField()),
                ('order', models.CharField(max_length=300)),
                ('reason', models.TextField()),
                ('date', models.DateField()),
                ('pdf_binary', models.BinaryField(default=b'')),
                ('proceeding', models.TextField()),
                ('password', models.TextField()),
                ('qrimg_binary', models.BinaryField(default=b'')),
                ('code', models.TextField(default='00000000000')),
                ('stage', models.IntegerField(default=0)),
                ('view', models.BooleanField(default=False)),
                ('n_ticket', models.CharField(default='0000000000', max_length=30)),
                ('route', models.CharField(default='treasury', max_length=50)),
                ('monto', models.IntegerField(default=0)),
                ('id_admin_turn', models.IntegerField(default=0)),
                ('pay_type', models.CharField(default='deposito', max_length=50)),
                ('img_pay', models.BinaryField(default=b'')),
                ('report_state', models.BooleanField(default=False)),
                ('finisher_state', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
