# Generated by Django 4.2 on 2023-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
