# Generated by Django 4.2 on 2023-06-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fut_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='n_ticket',
            field=models.CharField(default='0000000000', max_length=30),
        ),
        migrations.AddField(
            model_name='fut',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
