# Generated by Django 4.2 on 2023-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_fut_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='tupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_incolucradas', models.CharField(max_length=100)),
                ('tipo_de_servicio', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('duracion_de_tramite', models.IntegerField()),
                ('procedimiento', models.CharField(max_length=200)),
            ],
        ),
    ]
