# Generated by Django 4.2 on 2023-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_fut_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='id_admin_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fut',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
