# Generated by Django 4.2 on 2023-11-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fut_id_admin_turn_fut_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='img_pay',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='fut',
            name='pay_type',
            field=models.CharField(default='deposito', max_length=50),
        ),
    ]
