# Generated by Django 4.2 on 2023-11-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fut_img_pay_fut_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='report_state',
            field=models.BooleanField(default=False),
        ),
    ]
