# Generated by Django 4.2 on 2023-11-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_fut_report_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='finisher_state',
            field=models.BooleanField(default=False),
        ),
    ]
