# Generated by Django 4.2 on 2023-11-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_fut_finisher_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tupa',
            name='require_attach',
            field=models.BooleanField(default=False),
        ),
    ]
