# Generated by Django 4.2 on 2024-01-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_tupa_require_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='full_name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='fut',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
