# Generated by Django 4.2 on 2024-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_fut_full_name_alter_fut_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fut',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
