# Generated by Django 4.2 on 2024-02-02 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('fullname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=35)),
                ('position', models.CharField(choices=[('treasury', 'Tesoreria'), ('secretary', 'Secretaria'), ('direction', 'Direccion')], max_length=25)),
                ('phone', models.CharField(max_length=12)),
                ('dni', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('code', models.CharField(default=myapp_admin.models.generate_code, max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_creator', models.CharField(max_length=60)),
                ('charge', models.CharField(max_length=60)),
                ('tittle', models.CharField(max_length=150)),
                ('state', models.BooleanField(default=False)),
                ('num_ticket', models.IntegerField()),
                ('view', models.BooleanField(default=False)),
                ('code', models.CharField(default=myapp_admin.models.generate_code_2, max_length=6)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.admins')),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_desarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desarrollo', models.TextField()),
                ('charge', models.CharField(max_length=60)),
                ('date', models.DateTimeField(null=True)),
                ('img_identify', models.BinaryField(default=b'')),
                ('img_attach', models.BinaryField(default=b'')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('desarrollo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.ticket_desarrollo')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_notififcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150)),
                ('desarrollo', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('emitido', models.CharField(max_length=60)),
                ('charge', models.CharField(max_length=60)),
                ('view', models.BooleanField(default=False)),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_attach_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('the_type', models.CharField(max_length=10)),
                ('the_size', models.IntegerField()),
                ('the_file', models.BinaryField(default=b'')),
                ('desarrollo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.ticket_desarrollo')),
            ],
        ),
        migrations.CreateModel(
            name='secretary_send_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=300)),
                ('the_file', models.BinaryField(default=b'')),
                ('coment', models.TextField()),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
        migrations.CreateModel(
            name='ruta_tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('reception', models.DateTimeField()),
                ('exit', models.DateTimeField(null=True)),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
        migrations.CreateModel(
            name='reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssage', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('id_destino_admin', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('fut_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('id_origen_admin', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.admins')),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('reception', models.DateTimeField()),
                ('exit', models.DateTimeField(null=True)),
                ('state', models.BooleanField()),
                ('num', models.IntegerField()),
                ('stage', models.IntegerField(default=0)),
                ('route', models.CharField(default='noname', max_length=40)),
                ('fut_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150)),
                ('date', models.DateTimeField(null=True)),
                ('emitido', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=150)),
                ('view', models.BooleanField(default=False)),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=40)),
                ('pdf_binary', models.BinaryField(default=b'')),
                ('final_pdf_binary', models.BinaryField(default=b'')),
                ('state', models.BooleanField()),
                ('fut_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
        migrations.CreateModel(
            name='direction_public_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=300)),
                ('the_file', models.BinaryField(default=b'')),
                ('expediente', models.CharField(max_length=50)),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
    ]
