# Generated by Django 4.2 on 2023-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='dni',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='admins',
            name='fullname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='admins',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admins',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='admins',
            name='position',
            field=models.CharField(max_length=25),
        ),
    ]
