# Generated by Django 4.2 on 2023-05-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fut_email'),
        ('myapp_admin', '0003_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='fut_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.fut'),
        ),
    ]
