# Generated by Django 4.2 on 2023-05-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0004_process_fut_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
