# Generated by Django 4.2 on 2023-05-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0005_process_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='exit',
            field=models.DateTimeField(null=True),
        ),
    ]
