# Generated by Django 4.2 on 2023-06-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0006_alter_process_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='position',
            field=models.CharField(choices=[('treasury', 'Tesoreria'), ('secretary', 'Secretaria'), ('direction', 'Direccion')], max_length=25),
        ),
    ]
