# Generated by Django 4.2 on 2023-06-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0007_alter_admins_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='code',
            field=models.CharField(default='000', max_length=7),
        ),
    ]
