# Generated by Django 4.2 on 2023-06-09 14:11

from django.db import migrations, models
import myapp_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0008_admins_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='code',
            field=models.CharField(default=myapp_admin.models.generate_code, max_length=7, unique=True),
        ),
    ]
