# Generated by Django 4.2 on 2023-06-15 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_fut_route'),
        ('myapp_admin', '0009_alter_admins_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=40)),
                ('pdf_binary', models.BinaryField(default=b'')),
                ('state', models.BooleanField()),
                ('fut_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
    ]
