# Generated by Django 4.2 on 2023-06-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0010_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='route',
            field=models.CharField(default='noname', max_length=40),
        ),
    ]
