# Generated by Django 4.2 on 2023-11-16 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tupa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp_admin', '0012_document_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_creator', models.CharField(max_length=60)),
                ('charge', models.CharField(max_length=60)),
                ('tittle', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=50)),
                ('num_ticket', models.IntegerField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.admins')),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_desarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desarrollo', models.TextField()),
                ('charge', models.CharField(max_length=60)),
                ('date', models.DateTimeField(null=True)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('desarrollo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.ticket_desarrollo')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_attach_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('the_type', models.CharField(max_length=10)),
                ('the_size', models.IntegerField()),
                ('the_file', models.BinaryField(default=b'')),
                ('desarrollo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.ticket_desarrollo')),
            ],
        ),
    ]
