# Generated by Django 4.2 on 2023-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0013_ticket_ticket_desarrollo_ticket_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='area',
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
