# Generated by Django 4.2 on 2023-11-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_fut_user_id'),
        ('myapp_admin', '0014_remove_ticket_area_ticket_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssage', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('id_destino_admin', models.IntegerField()),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('id_origen_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.admins')),
            ],
        ),
    ]
