# Generated by Django 4.2 on 2023-11-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fut_id_admin_turn_fut_monto'),
        ('myapp_admin', '0015_reportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_admin_id', models.IntegerField()),
                ('desarrollo', models.TextField()),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('origin_dmin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.admins')),
            ],
        ),
    ]
