# Generated by Django 4.2 on 2023-11-22 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fut_img_pay_fut_pay_type'),
        ('myapp_admin', '0016_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='fut_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.fut'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='id_origen_admin',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myapp_admin.admins'),
        ),
    ]
