# Generated by Django 4.2 on 2023-11-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0017_alter_reportes_fut_id_alter_reportes_id_origen_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reports',
        ),
    ]
