# Generated by Django 4.2 on 2023-11-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0018_delete_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
