# Generated by Django 4.2 on 2023-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0019_reportes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
