# Generated by Django 4.2 on 2023-11-26 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_fut_report_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp_admin', '0020_ticket_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150)),
                ('date', models.DateTimeField(null=True)),
                ('emitido', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=150)),
                ('view', models.BooleanField(default=False)),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
