# Generated by Django 4.2 on 2023-11-29 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_fut_report_state'),
        ('myapp_admin', '0022_ticket_notififcation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ruta_tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('reception', models.DateTimeField()),
                ('exit', models.DateTimeField(null=True)),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
    ]
