# Generated by Django 4.2 on 2023-12-11 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_tupa_require_attach'),
        ('myapp_admin', '0024_secretary_send_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='direction_public_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=300)),
                ('the_file', models.BinaryField(default=b'')),
                ('expedinete', models.CharField(max_length=50)),
                ('fut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fut')),
            ],
        ),
    ]
