# Generated by Django 4.2 on 2023-12-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0025_direction_public_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction_public_document',
            old_name='expedinete',
            new_name='expediente',
        ),
    ]
