# Generated by Django 4.2 on 2023-12-19 22:49

from django.db import migrations, models
import myapp_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0026_rename_expedinete_direction_public_document_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_img_identify',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=myapp_admin.models.generate_code_2, max_length=6),
        ),
    ]
