# Generated by Django 4.2 on 2023-12-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0027_ticket_admin_img_identify_ticket_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='admin_img_identify',
        ),
        migrations.AddField(
            model_name='ticket_desarrollo',
            name='img_identify',
            field=models.BinaryField(default=b''),
        ),
    ]
