# Generated by Django 4.2 on 2024-01-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0028_remove_ticket_admin_img_identify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_desarrollo',
            name='img_attach',
            field=models.BinaryField(default=b''),
        ),
    ]
